"""extend_tn_chapter_section_title_to_text

Revision ID: 647ae17d3efd
Revises: b70479f1ff62
Create Date: 2026-01-29 16:41:45.049411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647ae17d3efd'
down_revision = 'b70479f1ff62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tn_chapter', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('tn_section', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tn_section', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('tn_chapter', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
