"""Rename groq_api_key to google_api_key

Revision ID: b70479f1ff62
Revises: f3e18a30d869
Create Date: 2026-01-29 14:50:59.141039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70479f1ff62'
down_revision = 'f3e18a30d869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_api_key', sa.String(length=255), nullable=True))
        batch_op.drop_column('groq_api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groq_api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('google_api_key')

    # ### end Alembic commands ###
