"""Add chapter_id to ChatSession for unified chat

Revision ID: c8d9e4a2f5b3
Revises: 647ae17d3efd
Create Date: 2026-01-31 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d9e4a2f5b3'
down_revision = '647ae17d3efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chat_session_chapter_id', 'chapter', ['chapter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_session_chapter_id', type_='foreignkey')
        batch_op.drop_column('chapter_id')

    # ### end Alembic commands ###
