"""Initial PostgreSQL schema

Revision ID: f3e18a30d869
Revises: 
Create Date: 2026-01-29 14:06:15.652169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e18a30d869'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_teacher', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), nullable=True),
    sa.Column('groq_api_key', sa.String(length=255), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_student',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'student_id')
    )
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='unique_enrollment')
    )
    op.create_table('syllabus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('syllabus_type', sa.String(length=10), nullable=True),
    sa.Column('clo_data', sa.JSON(), nullable=True),
    sa.Column('clo_stats', sa.JSON(), nullable=True),
    sa.Column('plo_data', sa.JSON(), nullable=True),
    sa.Column('weekly_plan', sa.JSON(), nullable=True),
    sa.Column('tn_data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('document_type', sa.String(length=50), server_default='general', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('quiz_data', sa.JSON(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_results', sa.JSON(), nullable=True),
    sa.Column('analysis_report_path', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tn_aa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id', 'number', name='uq_tn_aa_num')
    )
    op.create_table('tn_aap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id', 'number', name='uq_tn_aap_num')
    )
    op.create_table('tn_bibliography',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tn_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id', 'index', name='uq_tn_chapter_idx')
    )
    op.create_table('tn_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('methods', sa.JSON(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('measures', sa.JSON(), nullable=True),
    sa.Column('final_grade_formula', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id')
    )
    op.create_table('tn_syllabus_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('code_ue', sa.String(length=50), nullable=True),
    sa.Column('code_ecue', sa.String(length=50), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('option', sa.String(length=255), nullable=True),
    sa.Column('volume_presentiel', sa.String(length=50), nullable=True),
    sa.Column('volume_personnel', sa.String(length=50), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('credits', sa.Float(), nullable=True),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('teachers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('syllabus_id')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'student_id', name='uq_one_completed_quiz_per_student')
    )
    op.create_table('tn_chapter_aa',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('aa_id', sa.Integer(), nullable=False),
    sa.Column('description_override', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aa_id'], ['tn_aa.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['tn_chapter.id'], ),
    sa.PrimaryKeyConstraint('chapter_id', 'aa_id')
    )
    op.create_table('tn_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['tn_chapter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'index', name='uq_tn_section_idx')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_bloom_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('bloom_level', sa.String(length=50), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_clo_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('clo_name', sa.String(length=255), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choice_a', sa.Text(), nullable=True),
    sa.Column('choice_b', sa.Text(), nullable=True),
    sa.Column('choice_c', sa.Text(), nullable=True),
    sa.Column('correct_choice', sa.String(length=1), nullable=True),
    sa.Column('student_choice', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=20), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('bloom_level', sa.String(length=50), nullable=True),
    sa.Column('clo', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tn_section_aa',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('aa_id', sa.Integer(), nullable=False),
    sa.Column('description_override', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aa_id'], ['tn_aa.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['tn_section.id'], ),
    sa.PrimaryKeyConstraint('section_id', 'aa_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tn_section_aa')
    op.drop_table('quiz_question')
    op.drop_table('quiz_clo_statistic')
    op.drop_table('quiz_bloom_statistic')
    op.drop_table('chat_message')
    op.drop_table('tn_section')
    op.drop_table('tn_chapter_aa')
    op.drop_table('quiz')
    op.drop_table('notes')
    op.drop_table('chat_session')
    op.drop_table('tn_syllabus_admin')
    op.drop_table('tn_evaluation')
    op.drop_table('tn_chapter')
    op.drop_table('tn_bibliography')
    op.drop_table('tn_aap')
    op.drop_table('tn_aa')
    op.drop_table('document')
    op.drop_table('syllabus')
    op.drop_table('enrollment')
    op.drop_table('chapter')
    op.drop_table('user_session')
    op.drop_table('teacher_student')
    op.drop_table('course')
    op.drop_table('user')
    op.drop_table('classe')
    # ### end Alembic commands ###
